languageCode = "zh-Hans"
languageName = "简体中文"
languageDirection = "ltr"
weight = 2

title = "Molichaj"
copyright = "&copy; 2024 Congo contributors"

[params]
  dateFormat = "2006年1月2日"

  mainSections = ["posts"]
  description = "一款基于Tailwindcss的强大且轻量的Hugo主题"

[params.author]
  name = "茉莉茶酒"
  image = "img/author.jpg"
  headline = "当这一切都结束，请不要失落"
  bio = "当这一切都结束，请不要失落"
  #links = [
  #  { x-twitter = "https://twitter.com/" },
  #  { facebook = "https://facebook.com/" },
  #  { linkedin = "https://linkedin.com/" },
  #  { youtube = "https://youtube.com/" },
  #]
